spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update